apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: ibm-truststore-mgr
    app.kubernetes.io/managed-by: olm
    app.kubernetes.io/name: ibm-truststore-mgr
  name: ibm-truststore-mgr-worker
