apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: ibm-truststore-mgr
    app.kubernetes.io/managed-by: olm
    app.kubernetes.io/name: ibm-truststore-mgr
  name: ibm-truststore-mgr-worker
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - update
  - patch
- apiGroups:
  - truststore-mgr.ibm.com
  resources:
  - truststores
  verbs:
  - get
- apiGroups:
  - truststore-mgr.ibm.com
  resources:
  - truststores/status
  verbs:
  - get
  - patch
